server:

  port: 9527



spring:

  application:

    name: microservicecloud-zuul-gateway


eureka:

  client: #客户端注册进eureka服务列表内

    service-url:

      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  instance:

    instance-id: gateway-9527.com   #自定义服务名称信息

    prefer-ip-address: true     #访问路径可以显示IP地址



info:         #eureka info 页面 要显示的信息   使用插件 解析 以$ 符号开头和结尾的配置

  app.name: atguigu-microservicecloud

  company.name: www.atguigu.com

  build.artifactId: $project.artifactId$

  build.version: $project.version$
zuul:

  prefix: /atguigu    #添加前 缀

  ignored-services: "*"     #忽略多种 微服务名

  routes:

    mydept.serviceId: microservicecloud-dept    #微服务的 名 使用 /mydept/ 代替

    mydept.path: /mydept/**         # 最后的访问网址 http://myzuul.com:9527/atguigu/mydept/dept/get/1